/// Flutter icons OzapayIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OzapayIcons
///      fonts:
///       - asset: fonts/OzapayIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OzapayIcons {
  OzapayIcons._();

  static const _kFontFam = 'OzapayIcons';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_bold = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promote = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockwise = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wireless = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restore = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData price = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_left = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData get_pay = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_paste = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solana = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explorer = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
