targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern: 'Repository$|Bloc$|Cubit$|Factory$|Service$'
          # auto registers any class inside a file with a
          # name matches the given pattern
          file_name_pattern: '_repository$|_bloc$|_cubit$|_factory$|_service$'
